---
 28A. New England Cider
    :category_name: Specialty Cider and Perry

This is a cider made with characteristic New England apples for relatively high acidity, with adjuncts to raise alcohol levels.

Aroma/Flavor: A dry flavorful cider with robust apple character, strong alcohol, and derivative flavors from sugar adjuncts.
    :appearance: Clear to brilliant, pale to medium yellow.
    :mouthfeel: Substantial, alcoholic. Moderate tannin.
    :overall: Substantial body and character.
    :comments: Adjuncts may include white and brown sugars, molasses, small amounts of honey, and raisins. Adjuncts are intended to raise OG well above that which would be achieved by apples alone. This style is sometimes barrel-aged, in which case there will be oak character as with a barrel-aged wine. If the barrel was formerly used to age spirits, some flavor notes from the spirit (e.g., whisky or rum) may also be present, but must be subtle. Entrants MUST specify if the cider was barrel-fermented or aged. Entrants MUST specify carbonation level (still, petillant, or sparkling). Entrants MUST specify sweetness (dry, medium, or sweet).
    :varieties: Northern Spy, Roxbury Russet, Golden Russet
    :stats:      :og: 1.060 - 1.100
FG: 0.995 - 1.010        :abv: 7 - 13%

    :examples: There are no known commercial examples of New England Cider.
Back to top
28B. Fruit Cider
    :category_name: Specialty Cider and Perry

This is a cider with other fruits or fruit-juices added - for example, berry. Note that a "cider" made from a combination of apple and pear juice would be entered in this category since it is neither cider nor perry.

Aroma/Flavor: The cider character must be present and must fit with the other fruits. It is a fault if the adjuncts completely dominate; a judge might ask, "Would this be different if neutral spirits replaced the cider?" A fruit cider should not be like an alco-pop. Oxidation is a fault.
    :appearance: Clear to brilliant. Color appropriate to added fruit, but should not show oxidation characteristics. (For example, berries should give red-to-purple color, not orange.)
    :mouthfeel: Substantial. May be significantly tannic depending on fruit added.
    :overall: Like a dry wine with complex flavors. The apple character must marry with the added fruit so that neither dominates the other.
    :comments: Entrants MUST specify carbonation level (still, petillant, or sparkling). Entrants MUST specify sweetness (dry or medium). Entrants MUST specify what fruit(s) and/or fruit juice(s) were added.
    :stats:      :og: 1.045 - 1.070
FG: 0.995 - 1.010        :abv: 5 - 9%

    :examples: [US] West County Blueberry-Apple Wine (MA), AEppelTreow Red Poll Cran-Apple Draft Cider (WI), Bellwether Cherry Street (NY), Uncle John's Fruit Farm Winery Apple Cherry Hard Cider (MI)
Back to top
28C. Applewine
    :category_name: Specialty Cider and Perry

The term for this category is traditional but possibly misleading: it is simply a cider with substantial added sugar to achieve higher alcohol than a common cider.

Aroma/Flavor: Comparable to a Common Cider. Cider character must be distinctive. Very dry to slightly medium.
    :appearance: Clear to brilliant, pale to medium-gold. Cloudiness or hazes are inappropriate. Dark colors are not expected unless strongly tannic varieties of fruit were used.
    :mouthfeel: Lighter than other ciders, because higher alcohol is derived from addition of sugar rather than juice. Carbonation may range from still to champagne-like.
    :overall: Like a dry white wine, balanced, and with low astringency and bitterness.
    :comments: Entrants MUST specify carbonation level (still, petillant, or sparkling). Entrants MUST specify sweetness (dry or medium).
    :stats:      :og: 1.070 - 1.100
FG: 0.995 - 1.010        :abv: 9 - 12%

    :examples: [US] AEppelTreow Summer's End (WI), Wandering Aengus Pommeau (OR), Uncle John's Fruit House Winery Fruit House Apple (MI), Irvine's Vintage Ciders (WA)
Back to top
28D. Other Specialty Cider/Perry
    :category_name: Specialty Cider and Perry

This is an open-ended category for cider or perry with other adjuncts such that it does not fit any of the categories above. This includes the use of spices and/or other sweeteners. A cider with added honey may be entered here if the cider character remains dominant. Otherwise it should be entered as mead in the cyser sub-category.

Aroma/Flavor: The cider character must always be present, and must fit with adjuncts.
    :appearance: Clear to brilliant. Color should be that of a common cider unless adjuncts are expected to contribute color.
    :mouthfeel: Average body, may show tannic (astringent) or heavy body as determined by adjuncts.
    :comments: Entrants MUST specify all major ingredients and adjuncts. Entrants MUST specify carbonation level (still, petillant, or sparkling). Entrants MUST specify sweetness (dry or medium).
    :stats:      :og: 1.045 - 1.100
FG: 0.995 - 1.020        :abv: 5 - 12%

    :examples: [US] Red Barn Cider Fire Barrel (WA), AEppelTreow Pear Wine and Sparrow Spiced Cider (WI) 
