---
  lite american lager:
    :category: 1
    :category_name: Light Lager
    :subcategory: A
    :subcategory_name: Lite American Lager
    :aroma: Little to no malt aroma, although it can be grainy, sweet or corn-like if present. Hop aroma may range from none to a light, spicy or floral hop presence. Low levels of yeast character (green apples, DMS, or fruitiness) are optional but acceptable. No diacetyl.
    :appearance: Very pale straw to pale yellow color. White, frothy head seldom persists. Very clear.
    :flavor: Crisp and dry flavor with some low levels of grainy or corn-like sweetness. Hop flavor ranges from none to low levels. Hop bitterness at low level. Balance may vary from slightly malty to slightly bitter, but is relatively close to even. High levels of carbonation may provide a slight acidity or dry "sting." No diacetyl. No fruitiness.
    :mouthfeel: Very light body from use of a high percentage of adjuncts such as rice or corn. Very highly carbonated with slight carbonic bite on the tongue. May seem watery.
    :overall: Very refreshing and thirst quenching.
    :comments: A lower gravity and lower calorie beer than standard international lagers. Strong flavors are a fault. Designed to appeal to the broadest range of the general public as possible.
    :ingredients: Two- or six-row barley with high percentage (up to 40%) of rice or corn as adjuncts.
    :stats:
      :og: 7.1 - 10.0 P
      :bitterness: 8 - 12
      :fg:  -0.5 - 2.0 P
      :color: 2 - 3 SRM
      :abv: 2.8 - 4.2%
    :examples: "Bitburger Light, Sam Adams Light, Heineken Premium Light, Miller Lite, Bud Light, Coors Light, Baltika #1 Light, Old Milwaukee Light, Amstel Light"
  standard american lager:
    :display: Standard American Lager
    :aroma: Little to no malt aroma, although it can be grainy, sweet or corn-like if present. Hop aroma may range from none to a light, spicy or floral hop presence. Low levels of yeast character (green apples, DMS, or fruitiness) are optional but acceptable. No diacetyl.
    :appearance: Very pale straw to medium yellow color. White, frothy head seldom persists. Very clear.
    :flavor: Crisp and dry flavor with some low levels of grainy or corn-like sweetness. Hop flavor ranges from none to low levels. Hop bitterness at low to medium-low level. Balance may vary from slightly malty to slightly bitter, but is relatively close to even. High levels of carbonation may provide a slight acidity or dry "sting." No diacetyl. No fruitiness.
    :mouthfeel: Light body from use of a high percentage of adjuncts such as rice or corn. Very highly carbonated with slight carbonic bite on the tongue.
    :overall: Very refreshing and thirst quenching.
    :comments: Strong flavors are a fault. An international style including the standard mass-market lager from most countries.
    :ingredients: Two- or six-row barley with high percentage (up to 40%) of rice or corn as adjuncts.
    :stats:
      :og: 10.0 - 12.3 P
      :bitterness: 8 - 15 IBU
      :fg: 1.0 - 2.6 P
      :color: 2 - 4 SRM
      :abv: 4.2 - 5.3%

    :examples: "Pabst Blue Ribbon, Miller High Life, Budweiser, Baltika #3 Classic, Kirin Lager, Grain Belt Premium Lager, Molson Golden, Labatt Blue, Coors Original, Foster's Lager"

  premium american lager:
    :category: 1
    :category_name: Light Lager
    :subcategory: C
    :subcategory_name: Premium American Lager
    :aroma: Low to medium-low malt aroma, which can be grainy, sweet or corn-like. Hop aroma may range from very low to a medium-low, spicy or floral hop presence. Low levels of yeast character (green apples, DMS, or fruitiness) are optional but acceptable. No diacetyl.
    :appearance: Pale straw to gold color. White, frothy head may not be long lasting. Very clear.
    :flavor: Crisp and dry flavor with some low levels of grainy or malty sweetness. Hop flavor ranges from none to low levels. Hop bitterness at low to medium level. Balance may vary from slightly malty to slightly bitter, but is relatively close to even. High levels of carbonation may provide a slight acidity or dry "sting." No diacetyl. No fruitiness.
    :mouthfeel: Medium-light body from use of adjuncts such as rice or corn. Highly carbonated with slight carbonic bite on the tongue.
    :overall: Refreshing and thirst quenching, although generally more filling than standard/lite versions.
    :comments: Premium beers tend to have fewer adjuncts than standard/lite lagers, and can be all-malt. Strong flavors are a fault, but premium lagers have more flavor than standard/lite lagers. A broad category of international mass-market lagers ranging from up-scale American lagers to the typical "import" or "green bottle" international beers found in America.
    :ingredients: Two- or six-row barley with up to 25% rice or corn as adjuncts.
    :stats:
      :og: 11.4 - 13.7 P
      :bitterness: 15 - 25
      :fg: 2.1 - 3.1 P
      :color: 2 - 6 SRM
      :abv: 4.6 - 6%
    :examples: Full Sail Session Premium Lager, Miller Genuine Draft, Corona Extra, Michelob, Coors Extra Gold, Birra Moretti, Heineken, Beck's, Stella Artois, Red Stripe, Singha

  munich helles:
    :category: 1
    :category_name: Light Lager
    :subcategory: D
    :subcategory_name: Munich Helles
    :aroma: Pleasantly grainy-sweet, clean Pils malt aroma dominates. Low to moderately-low spicy noble hop aroma, and a low background note of DMS (from Pils malt). No esters or diacetyl.
    :appearance: Medium yellow to pale gold, clear, with a creamy white head.
    :flavor: Slightly sweet, malty profile. Grain and Pils malt flavors dominate, with a low to medium-low hop bitterness that supports the malty palate. Low to moderately-low spicy noble hop flavor. Finish and aftertaste remain malty. Clean, no fruity esters, no diacetyl.
    :mouthfeel: Medium body, medium carbonation, smooth maltiness with no trace of astringency.
    :overall: Malty but fully attenuated Pils malt showcase.
    :comments: Unlike Pilsner but like its cousin, Munich Dunkel, Helles is a malt-accentuated beer that is not overly sweet, but rather focuses on malt flavor with underlying hop bitterness in a supporting role.
    :history: Created in Munich in 1895 at the Spaten brewery by Gabriel Sedlmayr to compete with Pilsner-style beers.
    :ingredients: Moderate carbonate water, Pilsner malt, German noble hop varieties.
    :stats:
      :og: 11.2 - 12.3 P
      :bitterness: 16 - 22
      :fg: 2.1 - 3.1 P
      :color: 3 - 5 SRM
      :abv: 4.7 - 5.4%
    :examples: Weihenstephaner Original, Hacker-Pschorr M?nchner Gold, B?rgerbr?u Wolznacher Hell Naturtr?b, Mahr's Hell, Paulaner Premium Lager, Spaten Premium Lager, Stoudt's Gold Lager

  dortmunder export:
    :category: 1
    :categroy_name: Light Lager
    :subcategory: E
    :subcategory_name: Dortmunder Export
    :aroma: Low to medium noble (German or Czech) hop aroma. Moderate Pils malt aroma; can be grainy to somewhat sweet. May have an initial sulfury aroma (from water and/or yeast) and a low background note of DMS (from Pils malt). No diacetyl.
    :appearance: Light gold to deep gold, clear with a persistent white head.
    :flavor: Neither Pils malt nor noble hops dominate, but both are in good balance with a touch of malty sweetness, providing a smooth yet crisply refreshing beer. Balance continues through the finish and the hop bitterness lingers in aftertaste (although some examples may finish slightly sweet). Clean, no fruity esters, no diacetyl. Some mineral character might be noted from the water, although it usually does not come across as an overt minerally flavor.
    :mouthfeel: Medium body, medium carbonation.
    :overall: Balance and smoothness are the hallmarks of this style. It has the malt profile of a Helles, the hop character of a Pils, and is slightly stronger than both.
    :comments: Brewed to a slightly higher starting gravity than other light lagers, providing a firm malty body and underlying maltiness to complement the sulfate-accentuated hop bitterness. The term "Export" is a beer strength category under German beer tax law, and is not strictly synonymous with the "Dortmunder" style. Beer from other cities or regions can be brewed to Export strength, and labeled as such.
    :history: A style indigenous to the Dortmund industrial region, Dortmunder has been on the decline in Germany in recent years.
    :ingredients: Minerally water with high levels of sulfates, carbonates and chlorides, German or Czech noble hops, Pilsner malt, German lager yeast.
    :stats:
      :og: 11.9 - 13.7 P
      :bitterness: 23 - 30
      :fg: 2.6 - 3.8 P
      :color: 4 - 6 SRM
      :abv: 4.8 - 6.0%
    :examples: DAB Export, Dortmunder Union Export, Dortmunder Kronen, Ayinger Jahrhundert, Great Lakes Dortmunder Gold, Barrel House Duveneck's Dortmunder, Bell's Lager, Dominion Lager, Gordon Biersch Golden Export, Flensburger Gold 
