---
- :category: 17
  :subcategory: A
  :name: English Strong Ale
  :aroma: Malty - sweet with fruity esters, often with a complex blend of dried - fruit, caramel, nuts, toffee, and/or other specialty malt aromas. Some alcohol notes are acceptable, but shouldn't be hot or solventy. Hop aromas can vary widely, but typically have earthy, resiny, fruity, and/or floral notes. The balance can vary widely, but most examples will have a blend of malt, fruit, hops, and alcohol in varying intensities.
  :appearance: Deep gold to dark reddish - brown color (many are fairly dark). Generally clear, although darker versions may be almost opaque. Moderate to low cream - to light tan - colored head; average retention.
  :flavor: Medium to high malt character often rich with nutty, toffee, or caramel flavors. Light chocolate notes are sometimes found in darker beers. May have interesting flavor complexity from brewing sugars. Balance is often malty, but may be well hopped, which affects the impression of maltiness. Moderate fruity esters are common, often with a dark fruit or dried fruit character. The finish may vary from medium dry to somewhat sweet. Alcoholic strength should be evident, though not overwhelming. Diacetyl low to none, and is generally not desirable. 
  :mouthfeel: Medium to full, chewy body. Alcohol warmth is often evident and always welcome. Low to moderate carbonation.  Smooth texture.
  :overall_impression: An ale of respectable alcoholic strength, traditionally bottled - conditioned and cellared. Can have a wide range of interpretations, but most will have varying degrees of malty richness, late hops and bitterness, fruity esters, and alcohol warmth. Judges should allow for a significant range in character, as long as the beer is within the alcohol strength range and has an interesting 'English' character, it likely fits the style. The malt and adjunct flavors and intensity can vary widely, but any combination should result in an agreeable palate experience.
  :comments: Strength and character vary widely. Fits in the style space between normal gravity beers (strong bitters, brown ales, English porters) and barleywines. Can include pale malty - hoppy beers, English winter warmers, strong dark milds, smaller Burton ales, and other unique beers in the general gravity range that don't fit other categories. Traditionally a bottle - conditioned product suitable for cellaring.
  :history: The heritage varies since this category generally reflects a grouping of minor styles with limited production. Some are historical recreations while others are modern. Some directly descend from older styles such as Burton ales, while others maintain a historical connection with older beers. As a grouping, th e notion is relatively modern since beers of this strength category would not have been abnormal in past centuries.
  :characteristic_ingredients: Grists vary, often based on pale malt with caramel and specialty malts. Some darker examples suggest that dark malts (e.g., chocolate, black malt) may be appropriate, though sparingly so as to avoid an overly roasted character. Sugary adjuncts are common, as are starchy adjuncts (maize, flaked barley, wheat). Finish hops are traditionally English. 
  :style_comparison: Significant overlap in gravity with old ales, but not having a stale or aged character. A wide range of interpretations is possible. Should not be as rich or strong as an English Barleywine. Stronger than the stronger everyday beers (strong bitters, brown ales, porters). More specialty malt and/or sugar character than American Strong Ales.
  :vital_statistics:
    :og:
1.055 
-
1.080
    :bitterness:
30 
-
60
    :fg:
1.015 
-
1.022
    :color:
8 
-
22
    :abv:
5.5 
-
8.0% 
  :commercial_examples: 
Fuller's 1845, Young's Special London Ale, Harvey's
Elizabethan Ale, J.W. Lees Manchester Star, 
Sarah Hughes Dark Ruby Mild, Samuel Smith's Winter Welcome, Fuller's ESB, Adnams Broadside, Young's Winter Warmer
17B. Old Ale
  :aroma:
Malty
-
sweet with fruity esters, often with a complex blend of dried
-
fruit, v
inous, caramelly, molasses, nutty, toffee, light 
treacle, and/or other specialty malt aromas. Some alcohol and oxidative notes are acceptable, akin to those found in Sherry o
r 
Port. Hop aromas not usually present due to extended aging.
  :appearance:
Light am
ber to very dark reddish
-
brown color (most are fairly dark). Age and oxidation may darken the beer 
further. May be almost opaque (if not, should be clear). Moderate to low cream
-
to light tan
-
colored head; may be adversely 
affected by alcohol and age.
Flav
or: 
Medium to high malt character with a luscious malt complexity, often with nutty, caramelly and/or molasses
-
like flavors. 
Light chocolate or roasted malt flavors are optional, but should never be prominent. Balance is often malty
-
sweet, but may be 
well 
hopped (the impression of bitterness often depends on amount of aging). Moderate to high fruity esters are common, and 
may take on a dried
-
fruit or vinous character. The finish may vary from dry to somewhat sweet. Extended aging may contribute 
oxidative fl
avors similar to a fine old Sherry, Port or Madeira. Alcoholic strength should be evident, though not overwhelming. 
Diacetyl low to none. Some wood
-
aged or blended versions may have a lactic or Brettanomyces character; but this is optional 
and should not b
e too strong. Any acidity or tannin from age should be well
-
integrated and contribute to complexity in the flavor 
profile, not be a dominant experience.
  :mouthfeel:
Medium to full, chewy body, although older examples may be lower in body due to continued at
tenuation during 
conditioning. Alcohol warmth is often evident and always welcome. Low to moderate carbonation, depending on age and 
conditioning. Light acidity may be present, as well as some tannin if wood
-
aged; both are optional.
  :overall_impression:
An 
ale of moderate to fairly significant alcoholic strength, bigger than standard beers, though usually not as 
strong or rich as barleywine. Often tilted towards a maltier balance. "It should be a warming beer of the type that is best d
runk in 
half pints by a
warm fire on a cold winter's night" 
-
Michael Jackson.
  :comments: 
Strength and character varies widely. The predominant defining quality for this style is the impression of age, which 
can manifest itself in different ways (complexity, lactic, Brett, oxidat
ion, leather, vinous qualities, etc.). Even if these qualities are 
otherwise faults, if the resulting character of the beer is still pleasantly drinkable and complex, then those characteristic
s are 
acceptable. In no way should those allowable characteristi
cs be interpreted as making an undrinkably off beer as somehow in 
style. Old Peculier is a fairly unique type of beer that is quite different than other Old Ales.
  :history: 
Historically, an aged mild (when milds were stronger beers). Used as stock ales for 
blending or enjoyed at full strength 
(stale or stock refers to beers that were aged or stored for a significant period of time). 
  :characteristic_ingredients:
Composition varies, although generally similar to English Strong Ales. The age character is the 
bi
ggest driver of the final style profile, which is more handling than brewing. May be aged in wood, but should not have a stro
ng 
wood character.
  :style_comparison:
Roughly overlapping the English Strong Ale and the lower end of the English Barleywine styles,
but always 
having an aged quality. 
  :vital_statistics:
    :og:
1.055 
-
1.088
    :bitterness:
30 
-
60
    :fg:
1.015 
-
1.022
    :color:
10 
-
22
    :abv:
5.5 
-
9.0% 
  :commercial_examples: 
Gale's Prize Old Ale, Burton Bridge Olde Expensive, Marston Owd Roger, Greene King Strong 
Suffolk Al
e, Theakston Old Peculier
17C. Wee Heavy
  :aroma:
Deeply malty, with a strong caramel component. Lightly smoky secondary aromas may also be present, adding 
complexity. Caramelization often is mistaken for diacetyl, which should be low to none. Low to modera
te esters and alcohol are 
often present in stronger versions. Hops are very low to none, and can be slightly earthy or floral.
  :appearance:
Light copper to dark brown color, often with deep ruby highlights. Clear. Usually has a large tan head, which may 
not
persist. Legs may be evident in stronger versions.
  :flavor:
Richly malty with significant caramel (particularly in stronger versions). Hints of roasted malt may be present 
(sometimes perceived as a faint smoke character), as may some nutty character, all o
f which may last into the finish. Hop flavors 
and bitterness are low to medium
-
low, so the malt presence should dominate the balance. Diacetyl is low to none, although 
caramelization may sometimes be mistaken for it. Low to moderate esters and alcohol are 
usually present. Esters may suggest 
plums, raisins or dried fruit. The palate is usually full and sweet, but the finish may be sweet to medium
-
dry, sometimes with a 
light roasty
-
grainy note.
  :mouthfeel:
Medium
-
full to full
-
bodied, with some versions (but no
t all) having a thick, chewy viscosity. A smooth, alcoholic 
warmth is usually present and is quite welcome since it balances the malty sweetness. Moderate carbonation.
  :overall_impression:
Rich, malty, dextrinous, and usually caramel
-
sweet, these beers can 
give an impression that is suggestive of 
a dessert. Complex secondary malt and alcohol flavors prevent a one
-
dimensional quality. Strength and maltiness can vary, but 
should not be cloying or syrupy.
  :comments:
Also known as "strong Scotch ale." 
  :history: 
M
ore related to historical brews than the lower
-
strength Scottish ales, these beers have their roots in the strong ales of 
the 1700s and 1800s, although formulations and methods have changed. A premium product, often produced for export. Modern 
versions hav
e lower starting and finishing gravities than their historical ancestors.
  :characteristic_ingredients:
Well
-
modified pale malt, with roasted barley for color. May use some crystal malt for color 
adjustment. Slight smoke character may be present in some vers
ions, but derives from roasted grains or a long, vigorous boil. 
Peated malt is absolutely not traditional.
  :style_comparison:
Somewhat similar to an English Barleywine.
Vital Statistics
:
    :og:
1.070 
-
1.130
    :bitterness:
17 
-
35
    :fg:
1.018 
-
1.040
    :color:
14 
-
25
    :abv:
6.
5 
-
10%
  :commercial_examples:
Traquair House Ale, Belhaven Wee Heavy, McEwan's Scotch Ale, MacAndrew's Scotch Ale, Orkney 
Skull Splitter, Inveralmond Black Friar, Broughton Old Jock, Gordon Highland Scotch Ale, AleSmith Wee Heavy
17D. English Barleywine
Ar
oma:
Very rich and strongly malty, often with a caramel
-
like aroma in darker versions or a light toffee character in paler 
versions. May have moderate to strong fruitiness, often with a dark
-
or dried
-
fruit character, particularly in dark versions. The 
hop
aroma may range from mild to assertive, and is typically floral, earthy, or marmalade
-
like. Alcohol aromatics may be low to 
moderate, but are soft and rounded. The intensity of these aromatics often subsides with age. The aroma may have a rich character i
ncluding bready, toasty, toffee, and/or molasses notes. Aged versions may have a sherry
-
like quality, possibly vinous 
or port
-
like aromatics, and generally more muted malt aromas.
  :appearance:
Color may range from rich gold to very dark amber or even dark b
rown (often has ruby highlights, but should not 
be opaque). Low to moderate off
-
white head; may have low head retention. May be cloudy with chill haze at cooler temperatures, 
but generally clears to good to brilliant clarity as it warms. The color may appe
ar to have great depth, as if viewed through a thick 
glass lens. High alcohol and viscosity may be visible in "legs" when beer is swirled in a glass.
  :flavor:
Strong, intense, complex, multi
-
layered malt flavors ranging from bready, toffee, and biscuity in 
paler versions through 
nutty, deep toast, dark caramel, and/or molasses in darker versions. Moderate to high malty sweetness on the palate, although
the 
finish may be moderately sweet to moderately dry (depending on aging). Some oxidative or vinous flavors
may be present, and 
often complex alcohol flavors should be evident. Moderate to fairly high fruitiness, often with a dark
-
or dried
-
fruit character. 
Hop bitterness may range from just enough for balance to a firm presence; balance therefore ranges from m
alty to somewhat 
bitter. Pale versions are often more bitter, better attenuated, and might show more hop character than darker versions; howev
er, 
all versions are malty in the balance. Low to moderately high hop flavor, often floral, earthy, or marmalade
-
l
ike English varieties.
  :mouthfeel:
Full
-
bodied and chewy, with a velvety, luscious texture (although the body may decline with long conditioning). A 
smooth warmth from aged alcohol should be present. Carbonation may be low to moderate, depending on age and 
conditioning.
  :overall_impression:
A showcase of malty richness and complex, intense flavors. Chewy and rich in body, with warming alcohol 
and a pleasant fruity or hoppy interest. When aged, it can take on port
-
like flavors. A wintertime sipper.
  :comments:
T
he richest and strongest of the English Ales. The character of these ales can change significantly over time; both 
young and old versions should be appreciated for what they are. The malt profile can vary widely; not all examples will have 
all 
possible fla
vors or aromas. Paler varieties won't have the caramel and richer malt flavors, nor will they typically have the darker 
dried fruits 
-
don't expect flavors and aromatics that are impossible from a beer of that color. 
  :history: 
Strong ales of various formul
ations have long been brewed in England, and were known by several names. The modern 
barleywine traces back to Bass No. 1, which was first called a barleywine in 1903, although it had been made in the 1800s. 
Barleywines were darker beers until Tennant (now
Whitbread) first produced Gold Label, a gold
-
colored barleywine in 1951. 
Usually the strongest ale offered by a brewery, and in recent years many commercial examples are now vintage
-
dated and offered 
as a limited
-
release winter seasonal specialty. The ori
ginal barleywine style that inspired derivative variations in Belgium, the 
United States, and elsewhere in the world.
  :characteristic_ingredients: 
High
-
quality, well
-
modified pale malt should form the backbone of the grist, with judicious 
amounts of caramel
malts. Dark malts should be used with great restraint, if at all, as most of the color arises from a lengthy boil.  
English hops such as Northdown, Target, East Kent Goldings and Fuggles are typical. Characterful English yeast.
  :style_comparison: 
Although 
often a hoppy beer, the English Barleywine places less emphasis on hop character than the 
American Barleywine and features English hops. English versions can be darker, maltier, fruitier, and feature richer specialt
y 
malt flavors than American Barleywines.
  :vital_statistics:
    :og:
1.080 
-
1.120
    :bitterness:
35 
-
70
    :fg:
1.018 
-
1.030
    :color:
8 
-
22
    :abv:
8 
-
12%
  :commercial_examples:
Adnam's Tally Ho, Burton Bridge Thomas Sykes Old Ale, J.W. Lee's Vintage Harvest Ale, Fuller's 
Vintage Ale, Robinson's Old Tom, Fuller's Gold
en Pride, Whitbread Gold Label
