---
  dark: # american lager:
    :appearance: Deep amber to dark brown with bright clarity and ruby highlights. Foam stand may not be long lasting, and is usually light tan in color.
    :aroma: Little to no malt aroma. Medium-low to no roast and caramel malt aroma. Hop aroma may range from none to light spicy or floral hop presence. Can have low levels of yeast character (green apples, DMS, or fruitiness). No diacetyl. 
    :category: 4A
    :comments: A broad range of international lagers that are darker than pale, and not assertively bitter and/or roasted.
    :display: Dark American Lager
    :examples: "Dixie Blackened Voodoo, Shiner Bock, San Miguel Dark, Baltika #4, Beck's Dark, Saint Pauli Girl Dark, Warsteiner Dunkel, Heineken Dark Lager, Crystal Diplomat Dark Beer"
    :flavor: Moderately crisp with some low to moderate levels of sweetness. Medium-low to no caramel and/or roasted malt flavors (and may include hints of coffee, molasses or cocoa). Hop flavor ranges from none to low levels. Hop bitterness at low to medium levels. No diacetyl. May have a very light fruitiness. Burnt or moderately strong roasted malt flavors are a defect.
    :ingredients: Two- or six-row barley, corn or rice as adjuncts. Light use of caramel and darker malts. Commercial versions may use coloring agents. 
    :mouthfeel: Light to somewhat medium body. Smooth, although a highly-carbonated beer.
    :overall: A somewhat sweeter version of standard/premium lager with a little more body and flavor.
    :stats:
      :color: 14-22 SRM
      :abv: 4.2 - 6.0%
      :fg: 2.1 - 3.1 P
      :ibu: 8 - 20 IBU
      :og: 10.9 - 13.7 P
