---
 27A. Common Cider
    :category_name: Standard Cider and Perry
    :aroma: Sweet or low-alcohol ciders may have apple aroma and flavor. Dry ciders will be more wine-like with some esters. Sugar and acidity should combine to give a refreshing character, neither cloying nor too austere. Medium to high acidity.
    :flavor: Sweet or low-alcohol ciders may have apple aroma and flavor. Dry ciders will be more wine-like with some esters. Sugar and acidity should combine to give a refreshing character, neither cloying nor too austere. Medium to high acidity.
    :appearance: Clear to brilliant, pale to medium gold in color.
    :mouthfeel: Medium body. Some tannin should be present for slight to moderate astringency, but little bitterness.
    :overall: Variable, but should be a medium, refreshing drink. Sweet ciders must not be cloying. Dry ciders must not be too austere. An ideal cider serves well as a "session" drink, and suitably accompanies a wide variety of food.
    :comments: A common cider is made from culinary/table apples, with wild or crab apples often used for acidity/tannin balance.  Entrants MUST specify carbonation level (still, petillant, or sparkling). Entrants MUST specify sweetness (dry, medium, sweet).
    :varieties: Common (Winesap, Macintosh, Golden Delicious, Braeburn, Jonathan), multi-use (Northern Spy, Russets, Baldwin), crabapples, any suitable wildings.
    :stats:      :og: 1.045 - 1.065
FG: 1.000 - 1.020        :abv: 5 - 8%

    :examples: [US] Red Barn Cider Jonagold Semi-Dry and Sweetie Pie (WA), AEppelTreow Barn Swallow Draft Cider (WI), Wandering Aengus Heirloom Blend Cider (OR), Uncle John's Fruit House Winery Apple Hard Cider (MI), Bellwether Spyglass (NY), West County Pippin (MA), White Winter Hard Apple Cider (WI), Harpoon Cider (MA)
Back to top
27B. English Cider
    :category_name: Standard Cider and Perry
This includes the English "West Country" plus ciders inspired by that style. These ciders are made with bittersweet and bitter-sharp apple varieties cultivated specifically for cider making.

    :aroma: No overt apple character, but various flavors and esters that suggest apples. May have "smoky (bacon)" character from a combination of apple varieties and MLF. Some "Farmyard nose" may be present but must not dominate; mousiness is a serious fault. The common slight farmyard nose of an English West Country cider is the result of lactic acid bacteria, not a Brettanomyces contamination.
    :flavor: No overt apple character, but various flavors and esters that suggest apples. May have "smoky (bacon)" character from a combination of apple varieties and MLF. Some "Farmyard nose" may be present but must not dominate; mousiness is a serious fault. The common slight farmyard nose of an English West Country cider is the result of lactic acid bacteria, not a Brettanomyces contamination.
    :appearance: Slightly cloudy to brilliant. Medium to deep gold color.
    :mouthfeel: Full. Moderate to high tannin apparent as astringency and some bitterness. Carbonation still to moderate, never high or gushing.
    :overall: Generally dry, full-bodied, austere.
    :comments: Entrants MUST specify carbonation level (still or petillant). Entrants MUST specify sweetness (dry to medium). Entrants MAY specify variety of apple for a single varietal cider; if specified, varietal character will be expected.
    :varieties: Kingston Black, Stoke Red, Dabinett, Foxwhelp, Yarlington Mill, various Jerseys, etc.
    :stats:      :og: 1.050 - 1.075
FG: 0.995 - 1.010        :abv: 6 - 9%

    :examples: [US] Westcott Bay Traditional Very Dry, Traditional Dry and Traditional Medium Sweet (WA), Farnum Hill Extra-Dry, Dry, and Farmhouse (NH), Wandering Aengus Dry Cider (OR), Red Barn Cider Burro Loco (WA), Bellwether Heritage (NY); [UK] Oliver's Herefordshire Dry Cider, various from Hecks, Dunkerton, Burrow Hill, Gwatkin Yarlington Mill, Aspall Dry Cider
Back to top
27C. French Cider
    :category_name: Standard Cider and Perry

This includes Normandy styles plus ciders inspired by those styles, including ciders made by various techniques to achieve the French flavor profile. These ciders are made with bittersweet and bitter-sharp apple varieties cultivated specifically for cider making.

Traditional French procedures use small amounts of salt and calcium compounds (calcium chloride, calcium carbonate) to aid the process of pectin coagulation. These compounds may be used, pre-fermentation, but in limited quantity. It is a fault if judges can detect a salty or chalky taste.

    :aroma: Fruity character/aroma. This may come from slow or arrested fermentation (in the French technique of d?f?cation) or approximated by back sweetening with juice. Tends to a rich fullness.
    :flavor: Fruity character/aroma. This may come from slow or arrested fermentation (in the French technique of d?f?cation) or approximated by back sweetening with juice. Tends to a rich fullness.
    :appearance: Clear to brilliant, medium to deep gold color.
    :mouthfeel: Medium to full, mouth filling. Moderate tannin apparent mainly as astringency. Carbonation moderate to champagne-like, but at higher levels it must not gush or foam.
    :overall: Medium to sweet, full-bodied, rich.
    :comments: Entrants MUST specify carbonation level (petillant or full). Entrants MUST specify sweetness (medium, sweet). Entrants MAY specify variety of apple for a single varietal cider; if specified, varietal character will be expected.
    :varieties: Nehou, Muscadet de Dieppe, Reine des Pommes, Michelin, etc.
    :stats:      :og: 1.050 - 1.065
FG: 1.010 - 1.020        :abv: 3 - 6%

    :examples: [US] West County Reine de Pomme (MA), Rhyne Cider (CA); [France] Eric Bordelet (various), Etienne Dupont, Etienne Dupont Organic, Bellot
Back to top
27D. Common Perry
    :category_name: Standard Cider and Perry

Common perry is made from culinary/table fruit.

    :aroma: There is a pear character, but not obviously fruity. It tends toward that of a young white wine. No bitterness.
    :flavor: There is a pear character, but not obviously fruity. It tends toward that of a young white wine. No bitterness.
    :appearance: Slightly cloudy to clear. Generally quite pale.
    :mouthfeel: Relatively full, low to moderate tannin apparent as astringency.
    :overall: Mild. Medium to medium-sweet. Still to lightly sparkling. Only very slight acetification is acceptable. Mousiness, ropy/oily characters are serious faults.
    :comments: Entrants MUST specify carbonation level (still, petillant, or sparkling). Entrants MUST specify sweetness (medium or sweet).
    :varieties: Bartlett, Kiefer, Comice, etc.
    :stats:      :og: 1.050 - 1.060
FG: 1.000 - 1.020        :abv: 5 - 7%

    :examples: [US] White Winter Hard Pear Cider (WI), AEppelTreow Perry (WI), Blossomwood Laughing Pig Perry (CO), Uncle John's Fruit House Winery Perry (MI)
Back to top
27E. Traditional Perry
    :category_name: Standard Cider and Perry

Traditional perry is made from pears grown specifically for that purpose rather than for eating or cooking. Many "perry pears" are nearly inedible.

   :aroma: There is a pear character, but not obviously fruity. It tends toward that of a young white wine. Some slight bitterness.
   :flavor: There is a pear character, but not obviously fruity. It tends toward that of a young white wine. Some slight bitterness.
    :appearance: Slightly cloudy to clear. Generally quite pale.
    :mouthfeel: Relatively full, moderate to high tannin apparent as astringency.
    :overall: Tannic. Medium to medium-sweet. Still to lightly sparkling. Only very slight acetification is acceptable. Mousiness, ropy/oily characters are serious faults.
    :comments: Entrants MUST specify carbonation level (still, petillant, or sparkling). Entrants MUST specify sweetness (medium or sweet). Variety of pear(s) used must be stated.
    :varieties: Butt, Gin, Huffcap, Blakeney Red, etc.
    :stats:      :og: 1.050 - 1.070
FG: 1.000 - 1.020        :abv: 5 - 9%

    :examples: [France] Bordelet Poire Authentique and Poire Granit, Christian Drouin Poire, [UK] Gwatkin Blakeney Red Perry, Oliver's Blakeney Red Perry and Herefordshire Dry Perry
